2022-11-23 13:16:42 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002309D3B5790>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /api/5288891/envelope/
2022-11-23 13:16:42 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002309D36FBE0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /api/5288891/envelope/
2022-11-23 13:16:42 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002309D39A6A0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /api/5288891/envelope/
2022-11-23 16:34:30 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000269088EB9A0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /api/5288891/envelope/
2022-11-23 16:34:30 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000269088F77C0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /api/5288891/envelope/
2022-11-23 16:34:30 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000269088F7280>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /api/5288891/envelope/
