
2022-09-29 12:55:35,579 | 69908 | WARNING | Could not instantiate TBXLogger: No module named 'tensorboardX'.
{'extra_python_environs_for_driver': {}, 'extra_python_environs_for_worker': {}, 'num_gpus': 0, 'num_cpus_per_worker': 1, 'num_gpus_per_worker': 0, '_fake_gpus': False, 'custom_resources_per_worker': {}, 'placement_strategy': 'PACK', 'eager_tracing': False, 'eager_max_retraces': 20, 'tf_session_args': {'intra_op_parallelism_threads': 2, 'inter_op_parallelism_threads': 2, 'gpu_options': {'allow_growth': True}, 'log_device_placement': False, 'device_count': {'CPU': 1}, 'allow_soft_placement': True}, 'local_tf_session_args': {'intra_op_parallelism_threads': 8, 'inter_op_parallelism_threads': 8}, 'env': None, 'env_config': {}, 'observation_space': None, 'action_space': None, 'env_task_fn': None, 'render_env': False, 'clip_rewards': None, 'normalize_actions': True, 'clip_actions': False, 'disable_env_checking': False, 'num_workers': 1, 'num_envs_per_worker': 1, 'sample_collector': <class 'ray.rllib.evaluation.collectors.simple_list_collector.SimpleListCollector'>, 'sample_async': True, 'enable_connectors': False, 'rollout_fragment_length': 10, 'batch_mode': 'truncate_episodes', 'remote_worker_envs': False, 'remote_env_batch_wait_ms': 0, 'validate_workers_after_construction': True, 'ignore_worker_failures': False, 'recreate_failed_workers': False, 'restart_failed_sub_environments': False, 'num_consecutive_worker_failures_tolerance': 100, 'horizon': None, 'soft_horizon': False, 'no_done_at_end': False, 'preprocessor_pref': 'deepmind', 'observation_filter': 'NoFilter', 'synchronize_filters': True, 'compress_observations': False, 'enable_tf1_exec_eagerly': False, 'sampler_perf_stats_ema_coef': None, 'gamma': 0.99, 'lr': 0.0033333333333333335, 'train_batch_size': 32, 'model': {'_use_default_native_models': False, '_disable_preprocessor_api': False, '_disable_action_flattening': False, 'fcnet_hiddens': [256, 256], 'fcnet_activation': 'tanh', 'conv_filters': None, 'conv_activation': 'relu', 'post_fcnet_hiddens': [], 'post_fcnet_activation': 'relu', 'free_log_std': False, 'no_final_linear': False, 'vf_share_layers': True, 'use_lstm': False, 'max_seq_len': 20, 'lstm_cell_size': 256, 'lstm_use_prev_action': False, 'lstm_use_prev_reward': False, '_time_major': False, 'use_attention': False, 'attention_num_transformer_units': 1, 'attention_dim': 64, 'attention_num_heads': 1, 'attention_head_dim': 32, 'attention_memory_inference': 50, 'attention_memory_training': 50, 'attention_position_wise_mlp_dim': 32, 'attention_init_gru_gate_bias': 2.0, 'attention_use_n_prev_actions': 0, 'attention_use_n_prev_rewards': 0, 'framestack': True, 'dim': 84, 'grayscale': False, 'zero_mean': True, 'custom_model': None, 'custom_model_config': {}, 'custom_action_dist': None, 'custom_preprocessor': None, 'lstm_use_prev_action_reward': -1}, 'optimizer': {}, 'explore': True, 'exploration_config': {'type': 'StochasticSampling'}, 'input_config': {}, 'actions_in_input_normalized': False, 'postprocess_inputs': False, 'shuffle_buffer_size': 0, 'output': None, 'output_config': {}, 'output_compress_columns': ['obs', 'new_obs'], 'output_max_file_size': 67108864, 'evaluation_interval': None, 'evaluation_duration': 10, 'evaluation_duration_unit': 'episodes', 'evaluation_sample_timeout_s': 180.0, 'evaluation_parallel_to_training': False, 'evaluation_config': {}, 'off_policy_estimation_methods': {}, 'evaluation_num_workers': 0, 'always_attach_evaluation_results': False, 'in_evaluation': False, 'sync_filters_on_rollout_workers_timeout_s': 60.0, 'keep_per_episode_custom_metrics': False, 'metrics_episode_collection_timeout_s': 60.0, 'metrics_num_episodes_for_smoothing': 100, 'min_time_s_per_iteration': 5, 'min_train_timesteps_per_iteration': 0, 'min_sample_timesteps_per_iteration': 0, 'logger_creator': None, 'logger_config': None, 'log_level': 'WARN', 'log_sys_usage': True, 'fake_sampler': False, 'seed': None, '_tf_policy_handles_more_than_one_loss': False, '_disable_preprocessor_api': False, '_disable_action_flattening': False, '_disable_execution_plan_api': True, 'simple_optimizer': -1, 'monitor': -1, 'evaluation_num_episodes': -1, 'metrics_smoothing_episodes': -1, 'timesteps_per_iteration': -1, 'min_iter_time_s': -1, 'collect_metrics_timeout': -1, 'buffer_size': -1, 'prioritized_replay': -1, 'learning_starts': -1, 'replay_batch_size': -1, 'replay_sequence_length': None, 'prioritized_replay_alpha': -1, 'prioritized_replay_beta': -1, 'prioritized_replay_eps': -1, 'min_time_s_per_reporting': -1, 'min_train_timesteps_per_reporting': -1, 'min_sample_timesteps_per_reporting': -1, 'input_evaluation': -1, 'use_critic': True, 'use_gae': True, 'grad_clip': 30.0, 'lr_schedule': None, 'vf_loss_coeff': 0.5, 'entropy_coeff': 0.01, 'entropy_coeff_schedule': None, 'lambda': 1.0, 'input': 'sampler', 'multiagent': {'policies': {}, 'policy_map_capacity': 100, 'policy_map_cache': None, 'policy_mapping_fn': None, 'policies_to_train': None, 'observation_fn': None, 'replay_mode': 'independent', 'count_steps_by': 'env_steps'}, 'callbacks': <class 'ray.rllib.algorithms.callbacks.DefaultCallbacks'>, 'create_env_on_driver': False, 'custom_eval_function': None, 'framework': 'torch', 'num_cpus_for_driver': 1}
2022-09-29 12:55:37,953	INFO worker.py:1518 -- Started a local Ray instance.
[36m(pid=70094)
Traceback (most recent call last):
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 418, in setup
    self.workers = WorkerSet(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 125, in __init__
    self.add_workers(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 269, in add_workers
    self.foreach_worker(lambda w: w.assert_healthy())
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 391, in foreach_worker
    remote_results = ray.get([w.apply.remote(func) for w in self.remote_workers()])
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2277, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=70218, ip=10.197.106.213, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f4f6afcd390>)
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 613, in __init__
    self._build_policy_map(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1784, in _build_policy_map
    self.policy_map.create_policy(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/policy/policy_map.py", line 123, in create_policy
    self[policy_id] = create_policy_for_framework(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/utils/policy.py", line 80, in create_policy_for_framework
    return policy_class(observation_space, action_space, merged_config)
  File "/home/tuhe/Documents/mavi/src/raya3c/a3c_torch_policy.py", line 36, in __init__
    TorchPolicyV2.__init__(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 81, in __init__
    model, dist_class = self._init_model_and_dist_class()
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 436, in _init_model_and_dist_class
    model = self.make_model()
  File "/home/tuhe/Documents/mavi/src/raya3c/a3c_torch_policy.py", line 57, in make_model
    model = ModelCatalog.get_model_v2(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/models/catalog.py", line 482, in get_model_v2
    raise ValueError(
ValueError: `model_cls` must be a ModelV2 sub-class, but is <class '__main__.MyClass'>!
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/tuhe/Documents/mavi/src/raya3c/example.py", line 104, in <module>
    res.append(wfun(a))
  File "/home/tuhe/Documents/mavi/src/raya3c/example.py", line 48, in my_experiment
    trainer = config.build(env="CartPole-v1")
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm_config.py", line 307, in build
    return self.algo_class(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 308, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 157, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/tuhe/Documents/mavi/src/raya3c/a3c.py", line 161, in setup
    super().setup(config)
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 443, in setup
    raise e.args[0].args[2]
ValueError: `model_cls` must be a ModelV2 sub-class, but is <class '__main__.MyClass'>!
[36m(RolloutWorker pid=70218)[39m 2022-09-29 12:55:46,865	ERROR worker.py:756 -- Exception raised in creation task: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=70218, ip=10.197.106.213, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f4f6afcd390>)
[36m(RolloutWorker pid=70218)[39m   File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 613, in __init__
[36m(RolloutWorker pid=70218)[39m     self._build_policy_map(
[36m(RolloutWorker pid=70218)[39m   File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1784, in _build_policy_map
[36m(RolloutWorker pid=70218)[39m     self.policy_map.create_policy(
[36m(RolloutWorker pid=70218)[39m   File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/policy/policy_map.py", line 123, in create_policy
[36m(RolloutWorker pid=70218)[39m     self[policy_id] = create_policy_for_framework(
[36m(RolloutWorker pid=70218)[39m   File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/utils/policy.py", line 80, in create_policy_for_framework
[36m(RolloutWorker pid=70218)[39m     return policy_class(observation_space, action_space, merged_config)
[36m(RolloutWorker pid=70218)[39m   File "/home/tuhe/Documents/mavi/src/raya3c/a3c_torch_policy.py", line 36, in __init__
[36m(RolloutWorker pid=70218)[39m     TorchPolicyV2.__init__(
[36m(RolloutWorker pid=70218)[39m   File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 81, in __init__
[36m(RolloutWorker pid=70218)[39m     model, dist_class = self._init_model_and_dist_class()
[36m(RolloutWorker pid=70218)[39m   File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 436, in _init_model_and_dist_class
[36m(RolloutWorker pid=70218)[39m     model = self.make_model()
[36m(RolloutWorker pid=70218)[39m   File "/home/tuhe/Documents/mavi/src/raya3c/a3c_torch_policy.py", line 57, in make_model
[36m(RolloutWorker pid=70218)[39m     model = ModelCatalog.get_model_v2(
[36m(RolloutWorker pid=70218)[39m   File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/models/catalog.py", line 482, in get_model_v2
[36m(RolloutWorker pid=70218)[39m     raise ValueError(
[36m(RolloutWorker pid=70218)[39m ValueError: `model_cls` must be a ModelV2 sub-class, but is <class '__main__.MyClass'>!
Traceback (most recent call last):
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 418, in setup
    self.workers = WorkerSet(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 125, in __init__
    self.add_workers(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 269, in add_workers
    self.foreach_worker(lambda w: w.assert_healthy())
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 391, in foreach_worker
    remote_results = ray.get([w.apply.remote(func) for w in self.remote_workers()])
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2277, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=70218, ip=10.197.106.213, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f4f6afcd390>)
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 613, in __init__
    self._build_policy_map(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1784, in _build_policy_map
    self.policy_map.create_policy(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/policy/policy_map.py", line 123, in create_policy
    self[policy_id] = create_policy_for_framework(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/utils/policy.py", line 80, in create_policy_for_framework
    return policy_class(observation_space, action_space, merged_config)
  File "/home/tuhe/Documents/mavi/src/raya3c/a3c_torch_policy.py", line 36, in __init__
    TorchPolicyV2.__init__(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 81, in __init__
    model, dist_class = self._init_model_and_dist_class()
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 436, in _init_model_and_dist_class
    model = self.make_model()
  File "/home/tuhe/Documents/mavi/src/raya3c/a3c_torch_policy.py", line 57, in make_model
    model = ModelCatalog.get_model_v2(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/models/catalog.py", line 482, in get_model_v2
    raise ValueError(
ValueError: `model_cls` must be a ModelV2 sub-class, but is <class '__main__.MyClass'>!
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/tuhe/Documents/mavi/src/raya3c/example.py", line 104, in <module>
    res.append(wfun(a))
  File "/home/tuhe/Documents/mavi/src/raya3c/example.py", line 48, in my_experiment
    trainer = config.build(env="CartPole-v1")
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm_config.py", line 307, in build
    return self.algo_class(
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 308, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 157, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/tuhe/Documents/mavi/src/raya3c/a3c.py", line 161, in setup
    super().setup(config)
  File "/home/tuhe/.local/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 443, in setup
    raise e.args[0].args[2]
ValueError: `model_cls` must be a ModelV2 sub-class, but is <class '__main__.MyClass'>!
[36m(RolloutWorker pid=70218)[39m Overwritten model class creation! Perhaps we don't need to do this.